#!/usr/bin/env python3
"""
Deploy the 4-button-switch dimming automations.

Profile-driven so every room uses identical, verified logic:

    button 2 short  -> brightness_pct = max(5,   cur - 10)   (floor 5%, never off)
    button 2 double -> brightness_pct = 10
    button 3 short  -> brightness_pct = min(100, cur + 10)   (from off -> 10%)
    button 3 double -> brightness_pct = 100

Physical button N maps 1:1 to the ZHA `button_N` subtype on these TS0044
switches - verified against the basement/kitchen/office automations, whose
aliases all match their subtype exactly.

Usage:
    python3 deploy_dimmer.py                 # dry run, all profiles
    python3 deploy_dimmer.py living_room     # dry run, one profile
    python3 deploy_dimmer.py --apply living_room
    python3 deploy_dimmer.py --apply all

Writing an already-deployed profile is a no-op: the same automation ids are
overwritten with identical content.
"""
import json
import os
import sys
import urllib.error
import urllib.request

HA_URL = os.environ["HA_URL"].rstrip("/")
HA_TOKEN = os.environ["HA_TOKEN"]


PROFILES = {
    "bedroom": {
        "label": "Bedroom",
        "device_id": "df8a924c8a1d428e1a5defa76e4961af",
        "target": "light.bedroom_lights",
        "base_id": 1790279000001,
        # button 3 double press already existed here (id 1787103476395) and is
        # managed separately, so it is not generated by this profile.
        "skip": {"b3_double"},
    },
    "living_room": {
        "label": "Living room",
        "device_id": "342b0c83f8cf79e12bc305f1baea27e6",
        "target": "light.living_room_lights",
        "base_id": 1790365000001,
        "skip": set(),
    },
}


def cur_pct_template(target):
    return (
        "{{ ((state_attr('" + target + "', 'brightness') | float(0)) / 2.55)"
        " | round(0) | int }}"
    )


def device_trigger(device_id, subtype, press):
    return {
        "trigger": "device",
        "domain": "zha",
        "device_id": device_id,
        "type": press,
        "subtype": subtype,
    }


def build(profile):
    dev = profile["device_id"]
    target = profile["target"]
    label = profile["label"]
    base = profile["base_id"]
    cur = cur_pct_template(target)
    trace = {"stored_traces": 20}

    specs = {
        "b2_short": (
            base + 0,
            f"Automation {label} lights button 2 - dim -10%",
            f"{label} 4 button switch, button 2 single press: lower brightness "
            f"of {target} by 10 percentage points, never below 5%. Does "
            f"nothing while the lights are off.",
            {
                "triggers": [
                    device_trigger(dev, "button_2", "remote_button_short_press")
                ],
                "conditions": [
                    {"condition": "state", "entity_id": target, "state": "on"}
                ],
                "actions": [
                    {"variables": {"cur_pct": cur}},
                    {
                        "action": "light.turn_on",
                        "target": {"entity_id": target},
                        "data": {
                            "brightness_pct": "{{ [5, cur_pct - 10] | max }}"
                        },
                    },
                ],
                # Queued so a fast burst of presses steps once per press
                # instead of being dropped the way mode: single would.
                "mode": "queued",
                "max": 10,
                "trace": trace,
            },
        ),
        "b2_double": (
            base + 1,
            f"Automation {label} lights button 2 dbl - 10%",
            f"{label} 4 button switch, button 2 double press: set {target} "
            f"straight to 10% brightness.",
            {
                "triggers": [
                    device_trigger(dev, "button_2",
                                   "remote_button_double_press")
                ],
                "conditions": [],
                "actions": [
                    {
                        "action": "light.turn_on",
                        "target": {"entity_id": target},
                        "data": {"brightness_pct": 10},
                    }
                ],
                "mode": "single",
                "trace": trace,
            },
        ),
        "b3_short": (
            base + 2,
            f"Automation {label} lights button 3 - brighten +10%",
            f"{label} 4 button switch, button 3 single press: raise brightness "
            f"of {target} by 10 percentage points, capped at 100%. If the "
            f"lights are off this turns them on at 10%.",
            {
                "triggers": [
                    device_trigger(dev, "button_3", "remote_button_short_press")
                ],
                "conditions": [],
                "actions": [
                    {"variables": {"cur_pct": cur}},
                    {
                        "action": "light.turn_on",
                        "target": {"entity_id": target},
                        "data": {
                            "brightness_pct": "{{ [100, cur_pct + 10] | min }}"
                        },
                    },
                ],
                "mode": "queued",
                "max": 10,
                "trace": trace,
            },
        ),
        "b3_double": (
            base + 3,
            f"Automation {label} lights button 3 dbl - 100%",
            f"{label} 4 button switch, button 3 double press: set {target} "
            f"to 100% brightness.",
            {
                "triggers": [
                    device_trigger(dev, "button_3",
                                   "remote_button_double_press")
                ],
                "conditions": [],
                "actions": [
                    {
                        "action": "light.turn_on",
                        "target": {"entity_id": target},
                        "data": {"brightness_pct": 100},
                    }
                ],
                "mode": "single",
                "trace": trace,
            },
        ),
    }

    out = {}
    for key, (aid, alias, desc, body) in specs.items():
        if key in profile["skip"]:
            continue
        aid = str(aid)
        out[aid] = {"id": aid, "alias": alias, "description": desc, **body}
    return out


def api(method, path, payload=None):
    data = json.dumps(payload).encode() if payload is not None else None
    req = urllib.request.Request(
        HA_URL + path,
        data=data,
        method=method,
        headers={
            "Authorization": "Bearer " + HA_TOKEN,
            "Content-Type": "application/json",
        },
    )
    try:
        with urllib.request.urlopen(req, timeout=30) as r:
            body = r.read().decode()
            return r.status, (json.loads(body) if body.strip() else None)
    except urllib.error.HTTPError as e:
        return e.code, e.read().decode()


def main():
    args = [a for a in sys.argv[1:] if a != "--apply"]
    apply = "--apply" in sys.argv
    wanted = args[0] if args else "all"

    if wanted == "all":
        names = list(PROFILES)
    elif wanted in PROFILES:
        names = [wanted]
    else:
        sys.exit(f"unknown profile {wanted!r}; choose from {list(PROFILES)} or 'all'")

    planned = {}
    for name in names:
        autos = build(PROFILES[name])
        planned.update(autos)
        print(f"=== profile: {name} -> {PROFILES[name]['target']} ===")
        for aid, cfg in autos.items():
            print(f"  {aid}  {cfg['alias']}")

    if not apply:
        print("\nDRY RUN - pass --apply to write.")
        print(json.dumps(planned, indent=2))
        return

    for aid, cfg in planned.items():
        status, body = api("POST", f"/api/config/automation/config/{aid}", cfg)
        print(f"POST {aid}: http={status} {body}")
        if status != 200:
            sys.exit(f"FAILED writing {aid}")

    status, _ = api("POST", "/api/services/automation/reload", {})
    print(f"RELOAD: http={status}")


if __name__ == "__main__":
    main()
